/* ============================================================
   schools.js — pre-populated LA County high schools + their
   districts. Powers the searchable School dropdown and the
   auto-filled District dropdown in registration + Start a Club.
   ============================================================ */
var DISTRICTS = [
  'Palos Verdes Peninsula Unified School District', 'Torrance Unified School District',
  'Los Angeles Unified School District', 'Long Beach Unified School District',
  'Santa Monica-Malibu Unified School District', 'ABC Unified School District',
  'Glendale Unified School District', 'Pasadena Unified School District',
  'Beverly Hills Unified School District', 'Culver City Unified School District',
  'El Segundo Unified School District', 'Redondo Beach Unified School District',
  'Manhattan Beach Unified School District', 'Inglewood Unified School District',
  'Compton Unified School District', 'Downey Unified School District',
  'Centinela Valley Union High School District', 'Burbank Unified School District',
  'Norwalk-La Mirada Unified School District', 'Private / Independent'
];
/* Each: { n: school name, d: district } */
var SCHOOLS = [
  { n: 'Palos Verdes Peninsula High School', d: 'Palos Verdes Peninsula Unified School District' },
  { n: 'Palos Verdes High School', d: 'Palos Verdes Peninsula Unified School District' },
  { n: 'Rancho del Mar High School', d: 'Palos Verdes Peninsula Unified School District' },
  { n: 'Torrance High School', d: 'Torrance Unified School District' },
  { n: 'South High School (Torrance)', d: 'Torrance Unified School District' },
  { n: 'West High School (Torrance)', d: 'Torrance Unified School District' },
  { n: 'North High School (Torrance)', d: 'Torrance Unified School District' },
  { n: 'Kurt T. Shery High School', d: 'Torrance Unified School District' },
  { n: 'Redondo Union High School', d: 'Redondo Beach Unified School District' },
  { n: 'Mira Costa High School', d: 'Manhattan Beach Unified School District' },
  { n: 'El Segundo High School', d: 'El Segundo Unified School District' },
  { n: 'Culver City High School', d: 'Culver City Unified School District' },
  { n: 'Beverly Hills High School', d: 'Beverly Hills Unified School District' },
  { n: 'Santa Monica High School', d: 'Santa Monica-Malibu Unified School District' },
  { n: 'Malibu High School', d: 'Santa Monica-Malibu Unified School District' },
  { n: 'Olympic High School', d: 'Santa Monica-Malibu Unified School District' },
  { n: 'Leuzinger High School', d: 'Centinela Valley Union High School District' },
  { n: 'Lawndale High School', d: 'Centinela Valley Union High School District' },
  { n: 'Hawthorne High School', d: 'Centinela Valley Union High School District' },
  { n: 'Inglewood High School', d: 'Inglewood Unified School District' },
  { n: 'Morningside High School', d: 'Inglewood Unified School District' },
  { n: 'Compton High School', d: 'Compton Unified School District' },
  { n: 'Dominguez High School', d: 'Compton Unified School District' },
  { n: 'Centennial High School (Compton)', d: 'Compton Unified School District' },
  { n: 'Downey High School', d: 'Downey Unified School District' },
  { n: 'Warren High School', d: 'Downey Unified School District' },
  { n: 'La Mirada High School', d: 'Norwalk-La Mirada Unified School District' },
  { n: 'Norwalk High School', d: 'Norwalk-La Mirada Unified School District' },
  { n: 'Cerritos High School', d: 'ABC Unified School District' },
  { n: 'Whitney High School (Cerritos)', d: 'ABC Unified School District' },
  { n: 'Gahr High School', d: 'ABC Unified School District' },
  { n: 'Artesia High School', d: 'ABC Unified School District' },
  { n: 'Long Beach Polytechnic High School', d: 'Long Beach Unified School District' },
  { n: 'Woodrow Wilson High School (Long Beach)', d: 'Long Beach Unified School District' },
  { n: 'Millikan High School', d: 'Long Beach Unified School District' },
  { n: 'Lakewood High School', d: 'Long Beach Unified School District' },
  { n: 'Cabrillo High School (Long Beach)', d: 'Long Beach Unified School District' },
  { n: 'Jordan High School (Long Beach)', d: 'Long Beach Unified School District' },
  { n: 'California Academy of Mathematics and Science', d: 'Long Beach Unified School District' },
  { n: 'Glendale High School', d: 'Glendale Unified School District' },
  { n: 'Herbert Hoover High School (Glendale)', d: 'Glendale Unified School District' },
  { n: 'Crescenta Valley High School', d: 'Glendale Unified School District' },
  { n: 'Pasadena High School', d: 'Pasadena Unified School District' },
  { n: 'John Muir High School', d: 'Pasadena Unified School District' },
  { n: 'Blair High School (Pasadena)', d: 'Pasadena Unified School District' },
  { n: 'Marshall Fundamental Secondary School', d: 'Pasadena Unified School District' },
  { n: 'Burbank High School', d: 'Burbank Unified School District' },
  { n: 'John Burroughs High School', d: 'Burbank Unified School District' },
  { n: 'Venice High School', d: 'Los Angeles Unified School District' },
  { n: 'San Pedro High School', d: 'Los Angeles Unified School District' },
  { n: 'Hollywood High School', d: 'Los Angeles Unified School District' },
  { n: 'Fairfax High School', d: 'Los Angeles Unified School District' },
  { n: 'Alexander Hamilton High School', d: 'Los Angeles Unified School District' },
  { n: 'Palisades Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'University High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'Westchester Enriched Sciences Magnets', d: 'Los Angeles Unified School District' },
  { n: 'Narbonne High School', d: 'Los Angeles Unified School District' },
  { n: 'Phineas Banning High School', d: 'Los Angeles Unified School District' },
  { n: 'Carson High School', d: 'Los Angeles Unified School District' },
  { n: 'Gardena High School', d: 'Los Angeles Unified School District' },
  { n: 'Susan Miller Dorsey High School', d: 'Los Angeles Unified School District' },
  { n: 'Crenshaw High School', d: 'Los Angeles Unified School District' },
  { n: 'John C. Fremont High School', d: 'Los Angeles Unified School District' },
  { n: 'James A. Garfield High School', d: 'Los Angeles Unified School District' },
  { n: 'Theodore Roosevelt High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'Abraham Lincoln High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'Eagle Rock High School', d: 'Los Angeles Unified School District' },
  { n: 'John Marshall High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'Belmont High School', d: 'Los Angeles Unified School District' },
  { n: 'Los Angeles High School', d: 'Los Angeles Unified School District' },
  { n: 'Manual Arts High School', d: 'Los Angeles Unified School District' },
  { n: 'Thomas Jefferson High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'David Starr Jordan High School (Los Angeles)', d: 'Los Angeles Unified School District' },
  { n: 'Alain LeRoy Locke College Preparatory Academy', d: 'Los Angeles Unified School District' },
  { n: 'Washington Preparatory High School', d: 'Los Angeles Unified School District' },
  { n: 'Ulysses S. Grant High School', d: 'Los Angeles Unified School District' },
  { n: 'Van Nuys High School', d: 'Los Angeles Unified School District' },
  { n: 'Birmingham Community Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'Reseda Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'Grover Cleveland Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'William Howard Taft Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'Chatsworth Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'Granada Hills Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'El Camino Real Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'John F. Kennedy High School (Granada Hills)', d: 'Los Angeles Unified School District' },
  { n: 'James Monroe High School', d: 'Los Angeles Unified School District' },
  { n: 'North Hollywood High School', d: 'Los Angeles Unified School District' },
  { n: 'Sylmar Charter High School', d: 'Los Angeles Unified School District' },
  { n: 'San Fernando High School', d: 'Los Angeles Unified School District' },
  { n: 'Verdugo Hills High School', d: 'Los Angeles Unified School District' },
  { n: 'Bravo Medical Magnet High School', d: 'Los Angeles Unified School District' },
  { n: 'Downtown Magnets High School', d: 'Los Angeles Unified School District' },
  { n: 'King/Drew Medical Magnet High School', d: 'Los Angeles Unified School District' },
  { n: 'Harbor Teacher Preparation Academy', d: 'Los Angeles Unified School District' },
  { n: 'Port of Los Angeles High School', d: 'Los Angeles Unified School District' },
  { n: 'Sotomayor Learning Academies', d: 'Los Angeles Unified School District' },
  { n: 'Chadwick School', d: 'Private / Independent' },
  { n: 'Harvard-Westlake School', d: 'Private / Independent' },
  { n: 'Loyola High School (Los Angeles)', d: 'Private / Independent' },
  { n: 'Marlborough School', d: 'Private / Independent' },
  { n: 'Windward School', d: 'Private / Independent' },
  { n: 'Brentwood School', d: 'Private / Independent' },
  { n: 'Crossroads School', d: 'Private / Independent' },
  { n: 'Campbell Hall School', d: 'Private / Independent' },
  { n: 'Notre Dame High School (Sherman Oaks)', d: 'Private / Independent' },
  { n: 'Bishop Montgomery High School', d: 'Private / Independent' },
  { n: 'St. Bernard High School', d: 'Private / Independent' },
  { n: 'Vistamar School', d: 'Private / Independent' },
  { n: 'Rolling Hills Preparatory School', d: 'Private / Independent' },
  { n: 'Mary Star of the Sea High School', d: 'Private / Independent' },
  { n: 'Cathedral High School (Los Angeles)', d: 'Private / Independent' },
  { n: 'Junipero Serra High School (Gardena)', d: 'Private / Independent' },
  { n: 'Da Vinci Schools', d: 'Private / Independent' }
];
function districtForSchool(name) {
  var s = SCHOOLS.find(function (x) { return x.n === name; });
  return s ? s.d : '';
}
/* Options HTML for a School <select>; `sel` is the currently-selected school name. */
function schoolOptionsHTML(sel) {
  return '<option value="">— Select your school —</option>' +
    SCHOOLS.map(function (s) { return '<option' + (s.n === sel ? ' selected' : '') + '>' + s.n + '</option>'; }).join('') +
    '<option value="Other"' + (sel === 'Other' ? ' selected' : '') + '>Other / Not listed</option>';
}
function districtOptionsHTML(sel) {
  return '<option value="">— Select district —</option>' +
    DISTRICTS.map(function (d) { return '<option' + (d === sel ? ' selected' : '') + '>' + d + '</option>'; }).join('') +
    '<option value="Other"' + (sel === 'Other' ? ' selected' : '') + '>Other</option>';
}
